# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: CoinTossIndexer
description: Real-time indexer for TheOnePercent CoinToss gaming protocol

# Global contract definitions
contracts:
  - name: CoinToss
    abi_file_path: ./abis/cointoss-abi.json
    handler: ./src/EventHandlers.ts
    events:
      # Pool Lifecycle Events
      - event: PoolCreated
      - event: PlayerJoined
      - event: PoolActivated
      - event: PoolAbandoned
      - event: GameCompleted

      # Game Mechanics Events
      - event: PlayerMadeChoice
      - event: RoundResolved

      # Creator/Staking Events
      - event: StakeDeposited
      - event: StakeWithdrawn
      - event: CreatorRewardClaimed
      - event: CreatorVerified
      - event: VerificationBonusApplied

      # System Events
      - event: ProjectPoolUpdated
      - event: ScopeUpdated
      - event: OwnershipTransferred

networks:
  # Celo Alfajores Testnet
  - id: 44787
    start_block: 25000000  # Recent block for faster initial sync
    contracts:
      - name: CoinToss
        address: 0x3331C7DF7Ae57F18B5948eE6F3bfd2Eb1fbc2B20

  # Celo Mainnet
  - id: 42220
    start_block: 25000000  # Recent block for faster initial sync
    contracts:
      - name: CoinToss
        address: 0xe5273E84634D9A81C09BEf46aA8980F1270b606A

# Enable unordered multichain mode for real-time indexing across both networks
unordered_multichain_mode: true

# Enable preload optimization for faster indexing
# Note: Handlers will run twice, so we'll use Effect API for external calls
preload_handlers: true

# Optional: Configure rollback handling for chain reorganizations
rollback_on_reorg: true

# Optional: Set sync interval for real-time updates (default: 1000ms)
sync_interval_ms: 500