[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.19"

# Optimizer settings to reduce contract size
optimizer = true
optimizer_runs = 200
via_ir = true

# Contract size optimization
bytecode_hash = "none"
strip_debug_info = true

[profile.size-optimized]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.19"

# Aggressive optimization for contract size
optimizer = true
optimizer_runs = 1  # Lower runs for smaller bytecode
via_ir = true
bytecode_hash = "none"
strip_debug_info = true

[rpc_endpoints]
celo_mainnet = "${CELO_MAINNET_RPC}"
celo_alfajores = "${CELO_ALFAJORES_RPC}"
local = "http://localhost:8545"

[etherscan]
celo = { key = "${CELOSCAN_API_KEY}", url = "https://api.celoscan.io/api" }